//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Lasaw.rc 使用
//
#define ID_BTN_CANCEL                   2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_LABEL_A            101
#define ID_INDICATOR_LABEL_B            102
#define ID_INDICATOR_LABEL_C            103
#define IDC_PICT00                      111
#define IDC_PICT01                      112
#define IDC_PICT02                      113
#define IDC_PICT03                      114
#define IDC_PICT04                      115
#define IDC_PICT05                      116
#define IDC_PICT06                      117
#define IDC_PICT07                      118
#define IDC_PICT10                      119
#define IDC_PICT11                      120
#define IDC_PICT12                      121
#define IDC_PICT13                      122
#define IDC_PICT14                      123
#define IDC_PICT15                      124
#define IDC_PICT16                      125
#define IDC_PICT17                      126
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ERRORINFO            129
#define IDR_LasawTYPE                   130
#define IDD_DIALOG_PROGRESS             139
#define IDD_DIALOG_IO                   166
#define IDD_DIALOGBAR                   167
#define IDB_LEDLOW                      169
#define IDB_LEDHIGH                     170
#define IDD_DIALOG_HOME                 172
#define IDD_DIALOG_LOGIN                180
#define IDD_DIALOG_MONITOR              310
#define IDD_DIALOG_PRODUCT              311
#define IDD_DIALOG_SETTING              312
#define IDD_DIALOG_MOTION               313
#define IDD_DIALOG_VISIONCTRL           314
#define IDD_DIALOG_DEBUG                316
#define IDD_DIALOG_PROJECTSETTING       317
#define IDB_COORD                       318
#define IDD_DIALOG_ALERT                319
#define IDR_MENU_MAIN                   319
#define IDB_COORD_BIG                   319
#define IDB_COORD_AXIS                  320
#define IDD_DIALOG_DXF                  320
#define IDR_MENU_USER                   321
#define IDD_DIALOG_CCDSET               322
#define IDD_DIALOG_MAIN                 324
#define IDI_ICON_ZOOM                   324
#define IDI_ICON_PAN                    325
#define IDR_CONTEXT_POPMUNE             335
#define IDC_STATIC_CONTAIN              1001
#define IDC_COMBO_CAMERA                1002
#define IDC_BUTTON_UPDATE               1002
#define IDC_BUTTON_MOVE_XL              1003
#define IDC_BUTTON_MOVE_XR              1004
#define IDC_COMBO_ORDER_SS              1004
#define IDC_BUTTON_CACULATE1            1004
#define IDC_BUTTON_MOVE_YU              1005
#define IDC_BUTTON_CACULATE2            1005
#define IDC_COMBO_POLARITY              1005
#define IDC_COMBO_SEARCH_DIR            1006
#define IDC_BUTTON_MOVE_YD              1006
#define IDC_BUTTON_CACULATE3            1006
#define IDC_CHECK_MASK                  1007
#define IDC_BUTTON_CACULATE4            1007
#define IDC_GROUPBOX00                  1009
#define IDC_BUTTON_MAIN                 1009
#define IDC_GROUPBOX01                  1010
#define IDC_BUTTON_REGISTER             1010
#define IDC_EDIT_SCORES                 1011
#define IDC_STATIC_PRODUCT              1011
#define IDC_GROUPBOX10                  1012
#define IDC_RADIO_FRONT                 1012
#define IDC_GROUPBOX11                  1013
#define IDC_RADIO_BACK                  1013
#define IDC_EDIT_PANE_L                 1014
#define IDC_EDIT_PANE_W                 1015
#define IDC_BUTTON_GOPOSITION           1017
#define IDC_TAB_SETTING                 1017
#define IDC_EDIT_ERRORLIST              1017
#define IDC_STATIC_ERRORLIST            1018
#define IDC_BUTTON_SAVEPOSITION         1018
#define IDC_BUTTON_TEST                 1018
#define IDC_STATIC_TITLE                1019
#define IDC_COMBO_SPACING               1019
#define IDC_COMBO_PRJNAME               1019
#define IDC_EDIT_STRENGTH               1020
#define IDC_SPIN1                       1020
#define IDC_EDIT_GAP                    1021
#define IDC_SPIN2                       1021
#define IDC_EDIT_SEARCH_WIDTH           1022
#define IDC_SPIN3                       1022
#define IDC_EDIT_SEARCH_KERNEL          1023
#define IDC_SPIN4                       1023
#define IDC_SPIN5                       1024
#define IDC_EDIT_REFANGLE               1024
#define IDC_BUTTON_MOTION               1025
#define IDC_SPIN6                       1025
#define IDC_BUTTON_NEW                  1026
#define IDC_SPIN7                       1026
#define IDC_BUTTON_RELOAD               1027
#define IDC_SPIN8                       1027
#define IDC_EDIT_NEWPROJECT             1028
#define ID_BTN_APPLY                    1028
#define IDC_BUTTON_CANCEL               1029
#define IDC_BUTTON_TOOL                 1029
#define IDC_BUTTON_MATCH                1030
#define IDC_BUTTON_FINDTEST             1031
#define IDC_BUTTON_TURNOVER             1031
#define IDC_BUTTON_SEARCHRECT           1032
#define IDC_STATIC_LEFT                 1032
#define IDC_BUTTON_SEARCH_AREA          1033
#define IDC_STATIC_RIGHT                1033
#define IDC_BUTTON_TEMPLATERECT         1034
#define IDC_STATIC_LEFT3                1034
#define IDC_STATIC_DISPLAY              1035
#define IDC_STATIC_SUMMARY              1036
#define IDC_RICHEDIT_PROCESS            1037
#define IDC_BUTTON_EXPORT               1037
#define IDC_BUTTON_PAD_CHECK            1038
#define IDC_BUTTON_EXPORT2              1038
#define IDC_BUTTON_GETPOSITION          1039
#define IDC_EDIT_PROPORTION             1039
#define IDC_EDIT_MU_VEL                 1040
#define IDC_BUTTON_PROCESS              1040
#define IDC_EDIT_MIN_ANGLE              1040
#define IDC_EDIT_MU_ACVEL               1041
#define IDC_EDIT_CUT_STEP               1041
#define IDC_EDIT_AU_VEL                 1042
#define IDC_EDIT_MARKOFFSET_X           1042
#define IDC_EDIT_AU_ACVEL               1043
#define IDC_EDIT_MARKOFFSET_Y           1043
#define IDC_EDIT_MARKOFFSET_R           1044
#define IDC_STATIC_PATH                 1044
#define IDC_EDIT_PPI                    1045
#define IDC_EDIT_MARK_POSX              1045
#define IDC_EDIT_FREQ                   1046
#define IDC_EDIT_MARK_POSY              1046
#define IDC_EDIT_POWER                  1047
#define IDC_BUTTON_ZOOM                 1048
#define IDC_BUTTON_PAN                  1049
#define IDC_RADIO_CW                    1051
#define IDC_RADIO_CCW                   1052
#define IDC_CHECK00                     1054
#define IDC_CHECK01                     1055
#define IDC_PROGRESS                    1056
#define IDC_CHECK02                     1056
#define IDC_STATIC_MESSAGE              1057
#define IDC_CHECK03                     1057
#define IDC_ANIMATE                     1058
#define IDC_CHECK04                     1058
#define IDC_BUTTON_REVERSE              1058
#define IDC_CHECK05                     1059
#define IDC_CHECK06                     1060
#define IDC_BUTTON_SPLICE               1059
#define IDC_COMBO_LOCUS                 1060
#define IDC_CHECK07                     1061
#define IDC_EDIT_CCD1_OFFSETX           1061
#define IDC_COMBO_LOCUS_LAST            1061
#define IDC_CHECK10                     1062
#define IDC_EDIT_CCD1_OFFSETY           1062
#define IDC_CHECK11                     1063
#define IDC_EDIT_CCD2_OFFSETX           1063
#define IDC_CHECK12                     1064
#define IDC_EDIT_CCD2_OFFSETY           1064
#define IDC_CHECK13                     1065
#define IDC_EDIT_CCD3_OFFSETX           1065
#define IDC_CHECK14                     1066
#define IDC_EDIT_CCD3_OFFSETY           1066
#define IDC_CHECK15                     1067
#define IDC_EDIT_CCD4_OFFSETX           1067
#define IDC_CHECK16                     1068
#define IDC_EDIT_CCD4_OFFSETY           1068
#define IDC_CHECK17                     1069
#define IDC_EDIT_EXPOSURE1              1069
#define IDC_EDIT_LIGHT1                 1070
#define IDC_EDIT_EXPOSURE2              1071
#define IDC_EDIT_LIGHT2                 1072
#define IDC_EDIT_EXPOSURE3              1073
#define IDC_EDIT_LIGHT3                 1074
#define IDC_COMBO_PRODUCT_CHECK         1075
#define IDC_EDIT_EXPOSURE4              1075
#define IDC_EDIT_LIGHT4                 1076
#define IDC_STATIC_CIRCLETIME           1080
#define IDC_STATIC_QUANTITY             1081
#define IDC_BUTTON_RESET_COUNTER        1087
#define IDC_CHECK_IDLING                1089
#define IDC_BUTTON_AUTO                 1090
#define IDC_STATIC_ACTUAL_X             1091
#define IDC_BUTTON_STOP                 1091
#define IDC_STATIC_ACTUAL_Y             1092
#define IDC_CHECK_INCHING               1099
#define IDC_STATIC_TARGET               1100
#define IDC_COMBO_POSITION_TYPE         1101
#define IDC_BUTTON_APPLY                1104
#define IDC_BUTTON_LASERTEST            1106
#define IDC_STATIC_XPLIMIT              1112
#define IDC_STATIC_XNLIMIT              1113
#define IDC_STATIC_XHOME                1114
#define IDC_STATIC_YPLIMIT              1115
#define IDC_STATIC_YNLIMIT              1116
#define IDC_STATIC_YHOME                1117
#define IDC_STATIC_ZPLIMIT              1118
#define IDC_STATIC_ZNLIMIT              1119
#define IDC_STATIC_ZHOME                1120
#define IDC_BUTTON_LOGIN                1120
#define IDC_STATIC_XALARM               1121
#define IDC_STATIC_YALARM               1122
#define IDC_STATIC_ZALARM               1123
#define IDC_EDIT_PASSWORD               1129
#define IDC_EDIT_OLDPASSWORD            1130
#define IDC_COMBO_USERTYPE              1131
#define IDC_BUTTON_MOV_STOP             1139
#define IDC_CHECK_BINARY                1143
#define IDC_BUTTON_MODIFY               1144
#define IDC_CHECK_ANGLE_EXT             1145
#define IDC_CHECK_ANGLE_REL             1146
#define ID_EDIT_NEW                     32772
#define ID_EDIT_DELETE                  32773
#define ID_CMD_MOVETO                   32774
#define ID_BTN_GETCENTER                32775
#define ID_BTN_GETUPDATE                32776
#define ID_PROJECT_CONFIGURATION        32780
#define ID_PROJECT_NEW                  32781
#define ID_BUTTON_HOME                  32782
#define ID_BUTTON_AUTO                  32783
#define ID_BUTTON_LATEST                32784
#define ID_VIEW_IO                      32785
#define ID_RESET_STATUS                 32786
#define ID_RESET_PROCESS                32787
#define ID_BUTTON_STOP                  32788
#define ID_BUTTON_EMG                   32789
#define ID_MENUBUTTON_USER              32790
#define ID_USER_LOGIN                   32791
#define ID_USER_LOGOUT                  32792
#define ID_BUTTON_ZOOM                  32795
#define ID_VIEW_DXF                     32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
